#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/carsten/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
#wmnd &
#wmsystemtray &
# wmsmixer -w &
# idesk &
pulseaudio --start 
nm-applet &
xscreensaver -no-splash&
pa-applet &
xfce4-power-manager &
synapse -s &
pcmanfm -d &
mopidy -q &
nitrogen --restore &
# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/carsten/.fluxbox/log"
